# Generated by Django 3.0.4 on 2020-08-26 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100, verbose_name='First Name')),
                ('lname', models.CharField(max_length=100, verbose_name='Last Name')),
                ('phone', models.CharField(help_text='Start with country code eg:+255', max_length=100, verbose_name='Phone Number')),
                ('trips', models.CharField(choices=[('stone', 'Stone Town'), ('prison', 'Prison Island'), ('safari', 'Safari Blue'), ('johazi', 'Johazi Forest'), ('dolphin', 'Dolphin Tour'), ('spice', 'Spice Tour'), ('dhow', 'Dhow Sunset Cruise'), ('mnemba', 'Mnemba Island')], max_length=15, verbose_name='SELECT ACTIVITY')),
                ('adults', models.IntegerField(verbose_name='Adults')),
                ('child', models.IntegerField(verbose_name='Child')),
                ('infant', models.IntegerField(verbose_name='infants')),
                ('plan', models.TextField(verbose_name='TELL US ABOUT YOUR PLAN')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
            },
        ),
    ]
