# Generated by Django 3.1.5 on 2021-02-09 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100, verbose_name='Full Name')),
                ('phone', models.CharField(help_text='Start with country code eg:+255', max_length=100, verbose_name='Phone Number')),
                ('email', models.EmailField(max_length=100, verbose_name='Email Address')),
                ('trips', models.CharField(choices=[('stone', 'Stone Town'), ('prison', 'Prison Island'), ('safari', 'Safari Blue'), ('johazi', 'Johazi Forest'), ('dolphin', 'Dolphin Tour'), ('spice', 'Spice Tour'), ('dhow', 'Dhow Sunset Cruise'), ('mnemba', 'Mnemba Island')], max_length=15, verbose_name='SELECT ACTIVITY')),
                ('adults', models.PositiveIntegerField(verbose_name='Adults')),
                ('child', models.PositiveIntegerField(verbose_name='Children')),
                ('infant', models.PositiveIntegerField(verbose_name='Infants')),
                ('date', models.DateField(verbose_name='ARRIVAL DATE')),
                ('plan', models.TextField(verbose_name='TELL US ABOUT YOUR PLAN')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
            },
        ),
    ]
