# Generated by Django 3.0.4 on 2020-08-26 13:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='ARRIVAL DATE'),
            preserve_default=False,
        ),
    ]
