# Generated by Django 3.0.4 on 2020-03-23 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200229_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='published',
            field=models.DateTimeField(auto_now=True, verbose_name='Published date'),
        ),
    ]
